### ISSUE TITLE
Regarding the Agreeing to the EULA patch...

### ISSUE THREAD

**Issue by Titaniumtown** [notOM3GA/Plox#1]
(regarding this patch: https://github.com/notOM3GA/Plox/blob/master/Tuinity-Server-Patches/0008-Agree-to-the-EULA.patch)
I thought that (legally) automatically agreeing to an EULA in the form that patch does isn't allowed. Because an EULA is a contract between the user and the provider of a service/product, and making it so the user doesn't have to agree to the EULA when using a software that has an EULA (I would think) be illegal.

But I'm not a lawyer.

**Comment by notOM3GA** [comment]
Hey!

As this is the software for Ploxcraft, this is mainly used as a convince for us. Due to the question of legality, I will remove this patch from the public repo.

Thanks.

**Comment by notOM3GA** [comment]
Haha, my commit seems to be borked, will look at it later.

**Comment by Titaniumtown** [comment]
Ok lol
